[general]
root = "."
page-fallback = "./index.html"

[[advanced.headers]]
source = "/index.html"
[advanced.headers.headers]
Cache-Control = "no-cache, no-store, must-revalidate, proxy-revalidate"
Pragma = "no-cache"
Expires = "0"
