#!/bin/bash
# install service in dev container

cd /workspace

echo "Install pnpm..."
corepack prepare pnpm@10.13.1 --activate

echo "Add markdown-toc for Readme"
npm install -g markdown-toc

echo "Install static web server..."
curl --proto '=https' --tlsv1.2 -sSfL https://get.static-web-server.net | sh

echo "Install Playwright system dependencies..."
pnpm exec playwright install-deps

echo "Install application and dev tools..."
pnpm install

echo "Install Playwright dependencies..."
pnpm exec playwright install --with-deps

# create certificates
(cd .devcontainer && ./create_cert)
