services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile

    init: true

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Comment out the next line to use the root user for all processes.
    user: node

    # define environment variables
    environment:
      DATA_PORTAL_CONFIG_YAML: /workspace/.devcontainer/.dev_config.yaml

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)