name: Lint

on:
  push:

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Install node
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run Linter
        run: npm run lint
