name: Lint

on:
  push:

jobs:
  lint:
    name: Run Prettier and ESLint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11.8.0
          run_install: false
      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check formatting
        run: pnpm format:check
      - name: Run Linter
        run: pnpm lint
